### ISSUE TITLE
rich dependency is old

### ISSUE THREAD

**Issue by kimberlyJ69** [Fitzy1293/redditsfinder#1]
Why is it that redditsfinder has a dependency on rich with versions between 7.0.0 and 8.0.0? Since rich is way past those version-numbers now, many other programs will require newer versions of rich - and redditsfinder will cause an error during pip installs.

**Comment by Fitzy1293** [comment]
Thank you for informing me. It's actually awesome to see someone organically entering an issue!
This was my first project that I published with PIP, and I used poetry to manage the dependencies. 

- I thought that ^7.0.0 would be any version >= 7.0.0, including subsequent "new releases" (8.0.0, 9.0.0, etc.)
    - However it's really any version in the range [7.0.0, 8.0.0), so  it's requiring rich 7.x.x for no good reason.
    - I just learned that from a more thorough reading of [this.](https://python-poetry.org/docs/dependency-specification/)

I will fix this code below so that updates to dependencies won't make things incompatible system wide. I will also test that the new version of rich won't break any functionality for redditsfinder. I just tried it with the latest version that installs with pip, rich 11.0.0, and it works fine. 

```toml
[tool.poetry.dependencies]
# Updated Python version
python = "^3.6"
rich = "^7.0.0"
redditcleaner = "^1.1.2"
requests = "^2.24.0"
```
Will have one line changed `rich = "^7.0.0"` -> `rich = "*"` 

I may do this with requests too, if requests version 3.x.x ever comes out. 

```toml
[tool.poetry.dependencies]
# Updated Python version
python = "^3.6"
rich = "*"
redditcleaner = "^1.1.2"
requests = "^2.24.0"
```

I will have this updated within the next day or two.
